spring:
  datasource:
    #    url: jdbc:h2:mem:mydb #in-memory database
    url: jdbc:h2:file:./data/demo # use to save data between runs
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

